# ---meta---
pretrain_exp_name: igae-warmup 
exp_name: igae
pretrain: true
train: true
# ----------

dataset:
  name: train/objaverse
  subset: square128

  scene_repartition: 
    objaverse: [0, 2]

injection_dataset: 
  name: null
  max_img: 1000
  split_ratio: 0.9

vae:
  pretrained_model_name_or_path: ostris/vae-kl-f8-d16


# training
train_args:
  consistency:
    batch_size: 12

  injection:
    apply: false
    batch_size: 3
    
    losses:
      loss_mse: True
      loss_lpip: True
    
    regularizations:
      tv: True

  optim:
    n_epochs: 2

pretrain_args:
  injection:
    apply: false
  optim:
    n_epochs: 2

wandb:
  apply: true
  project_name: igae
  entity: criteo-3d